--!strict

--[[
	StateEvents - Centralized event names and state types for model-view communication

	This module provides type-safe event names and data types used by Models to broadcast
	state changes and Views to listen for updates. By centralizing these, we prevent typos
	and ensure type consistency across the codebase.

	Usage in Models (server):
		-- Event names are automatically generated by AbstractModel
		-- Types can be used for validation and documentation

	Usage in Views (client):
		local StateEvents = require(ReplicatedStorage.Shared.StateEvents)

		-- Use event name constants instead of magic strings
		local inventoryStateChanged = eventsFolder:WaitForChild(StateEvents.Inventory.EventName)

		-- Use exported types for type-safe handling
		inventoryStateChanged.OnClientEvent:Connect(function(data: StateEvents.InventoryData)
			updateUI(data.gold, data.treasure)
		end)
]]

-- Event Name Constants
local StateEvents = {
	Inventory = {
		EventName = "InventoryStateChanged",
	},
	Shrine = {
		EventName = "ShrineStateChanged",
	},
}

-- State Data Types
-- These match the structure broadcast by the corresponding models

export type InventoryData = {
	ownerId: string,
	gold: number,
	treasure: number,
}

export type ShrineData = {
	ownerId: string,
	treasure: number,
	userId: string,
}

return StateEvents
